#!/bin/bash

source ../../../.env

VIDEO_ENDPOINT="https://fal.run/fal-ai/veo3/fast"
SEED=88888

echo "📱 DIATOM: Generating Mobile Videos (9:16)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Regenerating ALL 24 videos in native portrait format"
echo "Using same visual prompts + seed 88888"
echo ""

# Extract visual prompts from script (condensed for video generation)
declare -a MOBILE_PROMPTS=(
    "Microscopic documentary cinematography, David Attenborough BBC style, crystalline beauty, scientific wonder aesthetic, macro photography perfection. Extreme macro establishing shot, microscope objective 40x magnification, slow zoom in from water droplet to reveal diatom. Single circular diatom (Coscinodiscus species) with intricate radial geometric pattern, golden-amber translucent glass shell, visible green chloroplasts inside, perfectly symmetrical, suspended in crystal clear water, gently rotating from frame 1. Microscopic view of seawater droplet, bright laboratory/sunlit water, crystal clear water with suspended particles, soft light diffusion. Revealing the hidden microscopic world, diatom slowly rotating to show geometric pattern, water molecules (barely visible), light rays, scattered micro-particles. Shallow depth of field (diatom sharp, water background soft blur), bright field microscopy with transmitted light from below, creating golden glow through glass shell, tone: awe-inspiring, artistic wonder, hidden beauty revelation. Color palette: golden-amber translucent glass shell, emerald-green chloroplasts, crystal clear water, soft white light. 16:9 cinematic, no speech, ambient only"
    
    "Scientific microscopic beauty, crystalline formation, macro documentary aesthetic with artistic flair. Extreme close-up on diatom shell structure, microscope 100x magnification, slow circular orbit around diatom. Circular diatom with geometric radial pattern, translucent golden-amber glass frustule (shell), intricate perforations in perfect symmetry, green chloroplasts visible through transparent walls, slowly rotating to show 3D structure, light refracting through glass from frame 1. Microscopic aquatic environment, bright transmitted light, clear water with light beams creating rainbow refraction through glass shell. Camera orbits diatom showing intricate glass architecture, light refracts creating spectrum colors, silicon dioxide molecules being deposited (artistic visualization), light rays. Very shallow depth of field (shell texture ultra-sharp, background soft), transmitted light from below with side illumination creating rainbow refractions through glass, tone: scientific wonder mixed with artistic appreciation, alchemy of nature. Color palette: golden-amber glass with rainbow refractions, emerald chloroplasts, spectrum rainbow highlights, crystal clear background. 16:9 cinematic, no speech, ambient only"
    
    "Kaleidoscopic microscopic montage, geometric pattern showcase, scientific art gallery aesthetic. Grid montage transitioning between different diatom species, microscope various magnifications, smooth transitions between different diatom patterns. Sequence of different diatom species: circular radial (Coscinodiscus), triangular (Triceratium), elongated pennate (Navicula), star-shaped, each showing unique geometric patterns, all golden-amber glass with green chloroplasts, each diatom rotating to show pattern, smooth transitions between species from frame 1. Microscopic view, artistic presentation, bright even illumination, clean clinical background, each diatom displayed like art pieces. Kaleidoscopic presentation of diverse diatom geometries, patterns morphing and transitioning, multiple diatom species, geometric pattern emphasis, light refractions. Sharp focus on each diatom pattern, bright field microscopy with artistic presentation lighting, tone: gallery exhibition, nature as supreme artist, mathematical beauty. Color palette: golden-amber glass shells in various geometries, emerald green chloroplasts, rainbow refractions, white background. 16:9 cinematic, no speech, ambient only"
    
    "Scientific cutaway visualization, technical microscopic documentation, educational beauty aesthetic. Side view cross-section revealing internal structure, microscope 60x with depth visualization, slow pull-apart animation showing two halves separating. Circular diatom shown in side profile, two golden-amber glass frustule halves (epitheca top, hypotheca bottom) visible fitting together like lid and bottom of petri dish, green chloroplasts inside, radial pattern visible on each half, from frame 1 shown as complete, then halves slowly separate to reveal structure. Microscopic view with technical visualization, clinical bright lighting, clear water, scientific documentary presentation. Two halves of shell slowly separate to show how they fit together, then reassemble, cross-section lines (artistic technical overlay), dimension indicators. Medium depth of field (both halves and interior visible), bright clinical lighting with slight rim lighting on glass edges, tone: educational wonder, engineering marvel, biological precision. Color palette: golden-amber glass shells (two distinct halves), emerald green interior chloroplasts, white clinical background. 16:9 cinematic, no speech, ambient only"
    
    "Microscopic time-lapse, construction process visualization, architectural documentary aesthetic. Close-up on forming diatom shell, microscope 80x magnification, static frame watching construction process. Young diatom in process of building new glass frustule, golden-amber glass shell gradually forming from center outward in radial pattern, visible silicon deposition creating geometric structure, green chloroplasts inside actively working, shell construction in progress from frame 1, radial pattern emerging gradually. Microscopic aquatic environment with visible light, bright active photosynthesis lighting, water with dissolved silicon particles (artistic visualization), sunlight penetrating. Time-lapse of shell formation, radial pattern building outward from center, silicon deposition visible, silicon dioxide molecules (visualized as golden particles), sunlight rays, water molecules. Shallow depth of field (forming shell sharp, background soft), transmitted light showing construction progress, slight glow during deposition, tone: creative process, architectural wonder, living alchemy. Color palette: forming golden-amber glass with areas of completion and incompletion, emerald green chloroplasts, golden silicon particles, soft blue water. 16:9 cinematic, no speech, ambient only"
    
    "Triumphant reveal, newborn beauty, artistic presentation, celebratory microscopic cinematography. Medium shot of complete new diatom, microscope 40x magnification, slow dolly-in celebrating the finished creation. Newly completed circular diatom with pristine golden-amber glass shell, perfectly symmetrical radial pattern, intricate geometric perforations, vibrant emerald-green chloroplasts, shell gleaming with fresh transparency, gently rotating in water from frame 1, showing off completed perfection. Open water microscopic environment, golden hour lighting (artistic), crystal clear water, gentle current, suspended particles catching light, celebratory atmosphere. Newborn diatom floating freely, rotating gracefully to show geometric perfection, light particles, water molecules, subtle rainbow refractions through shell. Shallow depth of field (diatom razor sharp, background dreamy soft), golden transmitted light with artistic rim lighting, creating halo effect, tone: triumphant, celebratory, newborn beauty, artistic achievement. Color palette: gleaming golden-amber glass shell with perfect clarity, vibrant emerald chloroplasts, golden light, soft blue water, rainbow highlights. 16:9 cinematic, no speech, ambient only"
    
    "Microscopic documentary cinematography, scientific cellular biology visualization, authentic laboratory microscopy aesthetic. Cutaway view showing interior through transparent shell, microscope 100x magnification, slow steady zoom into cell interior. Circular diatom with golden-amber translucent glass shell allowing clear view inside, numerous vibrant emerald-green chloroplasts (disc-shaped organelles) actively photosynthesizing, chloroplasts gently moving within cell from frame 1. Microscopic interior cellular view, bright transmitted light from below with sunlight penetrating water above, clinical scientific lighting showing cellular detail. Photosynthesis process visible, chloroplasts absorbing light and working, natural cellular activity. Selective depth of field (chloroplasts sharp focus, shell translucent frame), transmitted microscopy lighting creating natural light rays through water and glass, tone: quiet productivity, living factory, essential biological work, scientific wonder. Color palette: vibrant emerald-green chloroplasts, golden-amber shell frame, white transmitted light. 16:9 cinematic, no speech, ambient only"
    
    "Microscopic nature documentary, scientific visualization with scale revelation, authentic microscopy transitions to conceptual scale. Start extreme close-up on single diatom chloroplasts glowing green, microscope 100x, pull back revealing countless diatoms throughout water column. Single circular diatom with golden-amber glass shell and emerald chloroplasts working, camera pulls back showing hundreds of other diatoms (various shapes) all photosynthesizing simultaneously from frame 1, massive scale revelation. Microscopic view expanding to show ocean water filled with diatoms, bright transmitted light from sun above, countless glass shells catching light, scientific documentary scale visualization. Mass photosynthesis occurring, countless chloroplasts all producing oxygen, stunning density of life. Depth of field transitions from shallow (single diatom) to deep (countless diatoms visible), bright natural sunlight penetrating water column, transmitted microscopy at scale, tone: ecological revelation, invisible army, planetary importance, scientific awe. Color palette: emerald-green chloroplasts by thousands, golden-amber shells catching light, blue ocean water, bright sunlight. 16:9 cinematic, no speech, ambient only"
    
    "Microscopic documentary cinematography, cellular reproduction process, scientific time-lapse aesthetic, authentic mitosis visualization. Side view of circular diatom, microscope 60x magnification, static camera watching cell division process unfold. Circular diatom with golden-amber glass shell (two-piece frustule visible), emerald-green chloroplasts inside, from frame 1 the two shell halves beginning to separate slowly, cell preparing for division. Microscopic aquatic environment, bright transmitted light from below showing structural detail, clinical microscopy lighting revealing shell architecture during division. Cell division mitosis beginning, two-part shell slowly separating, chloroplasts duplicating inside, natural biological reproduction. Medium depth of field (both shell halves and interior visible clearly), bright field transmitted microscopy, natural biological process lighting, tone: reproductive miracle, precise biology, life creating life, scientific wonder. Color palette: golden-amber glass shell halves separating, emerald-green chloroplasts dividing, clear water, white transmitted light. 16:9 cinematic, no speech, ambient only"
    
    "Microscopic documentary cinematography, cellular construction process, scientific time-lapse of shell formation, authentic biological architecture. Split screen showing two daughter cells side by side, microscope 80x magnification, parallel views of new shell construction. Two new diatom cells each with one original golden-amber glass shell half, actively constructing new matching bottom halves from frame 1, radial pattern forming identically in both, emerald chloroplasts inside both cells. Microscopic aquatic environment with construction focus, bright transmitted light showing new glass deposition, clinical scientific lighting revealing formation process. New shell construction synchronized, radial geometric patterns forming identically, silicon deposition creating matching architecture in both cells. Sharp focus on both forming shells, bright field microscopy showing construction detail, natural biological process lighting, tone: genetic precision, mathematical perfection, DNA blueprint manifest, biological architecture marvel. Color palette: golden-amber original shells, forming golden-amber new shells, emerald-green chloroplasts, white transmitted light. 16:9 cinematic, no speech, ambient only"
    
    "Microscopic documentary cinematography, generational comparison visualization, scientific scale demonstration, authentic size variation. Side by side comparison showing three generations of diatoms, microscope 40x magnification, static frame showing size difference. Three circular diatoms in size sequence, all with same golden-amber glass shell pattern and emerald chloroplasts, from frame 1 positioned largest to smallest showing generational reduction, same radial geometry but different sizes. Microscopic aquatic environment, bright transmitted light showing all three clearly, clinical comparison lighting demonstrating size issue. Size comparison across generations, largest original, medium daughter, smallest granddaughter, all perfect geometry but shrinking. Clear depth of field showing all three in sharp focus, bright field transmitted microscopy, scientific comparison lighting, tone: biological constraint, shrinking problem, evolutionary challenge, gentle concern. Color palette: golden-amber shells in three sizes, emerald-green chloroplasts in all, clear water, white transmitted light. 16:9 cinematic, no speech, ambient only"
    
    "Microscopic documentary cinematography, dramatic biological transformation, scientific regeneration process, authentic auxospore formation. Medium shot of tiny diatom transforming, microscope 60x magnification, dynamic transformation sequence. Very small circular diatom with golden-amber shell and emerald chloroplasts, from frame 1 beginning to shed glass shell, cell expanding rapidly, naked cell growing large then building new full-size shell. Microscopic aquatic environment, bright transmitted light showing transformation clearly, clinical microscopy lighting revealing dramatic growth restoration. Shell shedding and regeneration, cell expansion, size restoration, new full-scale shell construction, biological reset. Medium depth of field (transforming cell sharp, background soft), bright field transmitted microscopy showing all phases, natural biological lighting, tone: dramatic solution, evolutionary genius, renewal and rebirth, problem solved. Color palette: golden-amber shell fragments, naked cell expanding, new golden-amber shell forming, emerald-green chloroplasts throughout, clear water. 16:9 cinematic, no speech, ambient only"
    
    "Microscopic documentary cinematography, death and sinking visualization, melancholic beauty aesthetic, authentic post-mortem drift. Medium wide shot following sinking shell, microscope perspective transitioning to water column scale, slow downward tracking. Empty circular diatom shell, golden-amber glass frustule intact and perfect, no chloroplasts inside (cell contents gone), from frame 1 slowly sinking rotating gently through water column, pristine but lifeless. Microscopic to macro scale transition, starting in bright surface waters descending into dimmer depths, transmitted light from above fading gradually, natural water column lighting. Empty shell drifting downward, gentle rotation, pristine geometric pattern preserved, solitary descent. Shallow depth of field (shell sharp, water gradient visible), natural downwelling light diminishing, transmitted light becoming weaker with depth, tone: melancholic beauty, death's dignity, life's end but structure preserved. Color palette: golden-amber empty glass shell, darkening blue water gradient, fading white light from above, increasing darkness below. 16:9 cinematic, no speech, ambient only"
    
    "Microscopic documentary cinematography, ocean floor accumulation visualization, scientific sediment layer aesthetic, authentic diatomaceous deposit. Wide shot of ocean floor sediment, microscope perspective showing surface detail, static frame showing accumulation. Ocean floor covered in countless diatom shells of many shapes and sizes, golden-amber glass frustules in layers, our circular radial diatom settling among many others from frame 1, incredible density of shells. Deep ocean floor microscopic view, dim transmitted light from distant surface, clinical low-light microscopy showing sediment detail, scientific sediment documentation. Shell accumulation, layers of glass frustules, geological deposition, countless billions of shells, vast microscopic necropolis. Medium depth of field (shells in foreground sharp, layers fading into background), low transmitted light from above, deep ocean floor lighting, tone: vast accumulation, geological time, countless lives, eternal rest together. Color palette: golden-amber shells in countless variations, deep blue-black water, dim white light from above, sediment grays. 16:9 cinematic, no speech, ambient only"
    
    "Microscopic documentary cinematography, fossilization process visualization, scientific diagenesis time-lapse, authentic geological transformation. Cross-section view of sediment layers compressing, microscopic to geological scale, slow compression visualization. Layers of golden-amber diatom shells in sediment, progressively more compressed in deeper layers, from frame 1 showing weight pressure from above, water being expelled, shells pressing together, transformation to solid rock. Microscopic cross-section view of sediment column, no external light (subsurface), scientific visualization lighting showing compression stages, geological process documentation. Compression and lithification, water expulsion, shells fusing together, glass becoming stone, geological time manifesting. Clear focus on layer transitions, scientific visualization lighting showing process stages, subsurface geological lighting, tone: deep time transformation, geological alchemy, impermanence becoming permanence, fossilization. Color palette: golden-amber shells darkening with depth, expelled water clear, compacted layers becoming white-gray stone, deep earth browns. 16:9 cinematic, no speech, ambient only"
    
    "Microscopic to macro documentary cinematography, scale transition dramatic reveal, authentic geological formation visualization. Extreme zoom out transition from microscopic to landscape scale, start microscope 100x end wide landscape, dramatic scale shift. Start on single fossilized diatom in white stone matrix, rapidly zoom out revealing countless shells in stone, continuing to reveal massive white cliff face, all made of compressed diatom shells, visible from frame 1 as camera pulls back through scales. Microscopic stone matrix transitioning to massive geological formation, bright daylight on white cliffs, natural outdoor lighting revealing massive scale of diatom deposit. Scale revelation, microscopic to mountain-scale, countless trillions of shells forming landscape, ultimate expression of accumulated microscopic art. Depth of field transitions from microscopic sharp to landscape deep focus, natural daylight illumination showing white cliffs, outdoor geological lighting, tone: scale shock, microscopic becomes massive, individual becomes eternal landscape, ultimate legacy. Color palette: white diatomaceous earth stone, individual golden-amber fossil shells visible at start, massive white cliffs, blue sky, green surroundings. 16:9 cinematic, no speech, ambient only"
    
    "Microscopic documentary cinematography, human use visualization montage, scientific application aesthetic, authentic product microscopy. Split screen or quick montage showing diatomaceous earth in various human products, microscope and macro views, transitions between applications. White diatomaceous earth powder under microscope showing individual fossil diatom shells (golden-amber glass structure preserved), from frame 1 transitioning between close-ups of powder in different applications, fossilized radial patterns still visible. Microscopic and product scale views, bright clinical lighting for scientific clarity, laboratory and product photography lighting, application documentation. Ancient shells in modern use, microscopic structure preserved after millions of years, geometric patterns still perfect in powder form, human applications. Sharp microscopic focus on fossil shells in powder, bright clinical laboratory lighting, scientific product visualization lighting, tone: ancient meeting modern, art becoming utility, deep time connecting to present day. Color palette: white diatomaceous earth powder, preserved golden-amber fossil shell structure visible under microscope, product contexts, bright clinical white lighting. 16:9 cinematic, no speech, ambient only"
    
    "Microscopic documentary cinematography, fossilized perfection closeup, scientific preservation aesthetic, authentic paleontology beauty. Extreme close-up on fossilized diatom in stone matrix, microscope 100x magnification, slow rotation showing preserved detail. Single fossilized circular diatom perfectly preserved in white stone matrix, golden-amber glass structure intact after millions of years, radial geometric pattern completely preserved every detail sharp, from frame 1 slowly rotating to show perfection of preservation. Fossilized in stone matrix under microscope, bright transmitted light showing preserved glass structure, clinical paleontological microscopy lighting, scientific preservation documentation. Perfect preservation, every geometric detail intact, mathematical precision survived deep time, glass outlasted everything. Extreme shallow depth of field (fossil shell ultra-sharp, stone matrix soft), bright field microscopy with transmitted light showing preserved structure, paleontological specimen lighting, tone: eternal beauty, mathematics transcends time, art becomes eternal, perfect preservation miracle. Color palette: white stone matrix, preserved golden-amber glass fossil, geometric pattern details sharp, bright white transmitted light. 16:9 cinematic, no speech, ambient only"
    
    "Microscopic documentary cinematography, return to life visualization, vibrant renewal aesthetic, authentic contemporary microscopy. Wide shot of sunlit surface waters, microscope perspective showing countless living diatoms, dynamic life-filled frame. Modern ocean water filled with living circular diatoms, all with brilliant golden-amber glass shells and vibrant emerald-green chloroplasts, from frame 1 countless individuals floating rotating photosynthesizing, incredible diversity of life, same species still thriving. Shallow sunlit ocean waters, bright transmitted light from sun above creating shimmering illumination, natural ocean microscopy lighting, vibrant life documentation. Living population thriving, countless individuals active and alive, photosynthesis ongoing, geometric perfection being created right now. Medium depth of field (nearest diatoms sharp, countless others visible in background), brilliant transmitted sunlight penetrating water, natural ocean lighting creating golden glow, tone: life continues, renewal and persistence, same art still being created, eternal cycle ongoing. Color palette: brilliant golden-amber living shells, vibrant emerald-green chloroplasts, bright blue sunlit water, golden transmitted sunlight. 16:9 cinematic, no speech, ambient only"
    
    "Microscopic documentary cinematography, multi-generational visualization, continuous creation aesthetic, authentic reproduction observation. Split view showing multiple diatoms simultaneously dividing and building shells, microscope 60x magnification, parallel life processes. Several circular diatoms at different stages, all with golden-amber shells and emerald chloroplasts, from frame 1 showing one dividing, one building new shell, one newly complete, all same geometric pattern, generational continuity. Microscopic sunlit ocean waters, bright transmitted light showing all stages clearly, clinical microscopy lighting documenting life cycle, scientific continuity visualization. Simultaneous reproduction and construction, multiple generations actively creating same geometric art, unbroken pattern transmission, genetic blueprint manifest across individuals. Medium depth of field showing multiple specimens, bright field transmitted microscopy showing all stages, natural scientific lighting, tone: unbroken continuity, genetic fidelity, pattern persistence across deep time, living tradition. Color palette: golden-amber shells in various completion stages, emerald-green chloroplasts in all living cells, bright blue water, white transmitted sunlight. 16:9 cinematic, no speech, ambient only"
    
    "Microscopic documentary cinematography, human scale to microscopic revelation, philosophical perspective aesthetic, authentic scale comparison. Dramatic transition from human perspective to microscopic reality, start macro beach scene transition to water drop microscopy, scale shift visualization. Start with human hand holding beach sand (containing diatom shells), rapidly transition to microscope view of water droplet revealing living diatoms with golden-amber shells and emerald chloroplasts, from frame 1 the transition showing connection between human world and microscopic artists unseen. Beach sand macro view transitioning to microscopic water drop, natural daylight transitioning to transmitted microscopy light, documentary perspective shift lighting, human to invisible connection. Scale revelation, human interaction with diatom world unknowing, microscopic artists revealed, invisible labor shown. Depth of field transitions from macro to microscopic, natural daylight to transmitted microscopy lighting, philosophical documentary lighting, tone: unseen labor, invisible contribution, human ignorance of microscopic heroes, grateful revelation. Color palette: beach sand beige transitioning to water drop clear, golden-amber diatom shells in both scales, emerald chloroplasts in living cells, natural to clinical lighting transition. 16:9 cinematic, no speech, ambient only"
    
    "Microscopic documentary cinematography, evolutionary diversity showcase, emergence and novelty aesthetic, authentic species variation. Montage showing unusual and newly discovered diatom species, microscope various magnifications, celebration of diversity and novelty. Several recently discovered or unusual diatom species, all with golden-amber glass shells and emerald chloroplasts but wildly different geometric patterns, from frame 1 transitioning between rare forms, asymmetric patterns, unusual shapes, evolutionary innovation visible. Microscopic waters from various environments, bright transmitted light showing pattern diversity, clinical microscopy celebrating variety, scientific discovery documentation. Evolutionary innovation ongoing, new geometric patterns emerging, natural selection creating new art forms, pattern diversity expanding. Sharp focus on each unique species, bright field transmitted microscopy showing innovative patterns, scientific diversity documentation lighting, tone: evolution active, innovation ongoing, art gallery expanding, endless creativity. Color palette: golden-amber shells in novel geometries, emerald-green chloroplasts in all, varied patterns and shapes, bright transmitted light. 16:9 cinematic, no speech, ambient only"
    
    "Microscopic documentary cinematography, abundance visualization at multiple scales, infinite pattern repetition aesthetic, authentic population density. Zoom out showing scale of diatom abundance, start single cell microscope view expand to show countless thousands, dramatic abundance revelation. Start with single perfect circular diatom with golden-amber shell and emerald chloroplasts, rapidly zoom out revealing more and more until frame filled with thousands, from frame 1 the zoom out showing incredible density, all same geometric perfection repeated infinitely. Microscopic view expanding to show population scale, bright transmitted light showing countless individuals, natural ocean microscopy at scale, abundance documentation. Infinite repetition of perfection, countless individuals all creating same geometric art, mathematical patterns repeated across vast population, abundance beyond comprehension. Depth of field expanding from single sharp subject to thousands visible, bright transmitted light illuminating entire population, natural microscopy showing scale, tone: infinite repetition, mathematical beauty multiplied, perfection abundant, overwhelming numbers. Color palette: golden-amber shells by thousands, emerald-green chloroplasts countless, bright blue water throughout, white transmitted sunlight. 16:9 cinematic, no speech, ambient only"
    
    "Microscopic documentary cinematography, final celebration of beauty, artistic tribute aesthetic, authentic microscopic perfection showcase. Hero shot of most beautiful diatom specimen, microscope 40x magnification, slow majestic rotation final homage. Single perfect circular diatom with brilliant golden-amber translucent glass shell, radial geometric pattern at its most beautiful, vibrant emerald-green chloroplasts glowing inside, from frame 1 slowly rotating showing perfection from all angles, ultimate expression of microscopic art, final celebration. Microscopic environment with perfect lighting, bright transmitted light creating optimal illumination, artistic yet authentic microscopy lighting, specimen showcase illumination. Final tribute, geometric perfection on display, glass art at its finest, chloroplasts vibrant, ultimate beauty achieved by nature. Extreme shallow depth of field (diatom razor sharp, background perfect soft), transmitted microscopy with artistic presentation lighting creating glory, scientific beauty celebration lighting, tone: final homage, artistic tribute, beauty celebrated, living art recognized, grateful wonder. Color palette: brilliant golden-amber glass shell, vibrant emerald-green chloroplasts, subtle rainbow refractions, perfect blue water, transmitted golden light. 16:9 cinematic, no speech, ambient only"
)

# Generate all 24 videos in parallel (8 at a time)
for i in {0..23}; do
    scene=$((i + 1))
    scene_num=$(printf "%02d" $scene)
    prompt="${MOBILE_PROMPTS[$i]}"
    
    (
        echo "📱 Scene $scene_num: Generating mobile video (9:16)..."
        
        response=$(curl -s -X POST "$VIDEO_ENDPOINT" \
            -H "Authorization: Key $FAL_API_KEY" \
            -H "Content-Type: application/json" \
            -d "{
                \"prompt\": \"$prompt\",
                \"duration\": 8,
                \"aspect_ratio\": \"9:16\",
                \"resolution\": \"1080p\",
                \"seed\": $SEED
            }")
        
        video_url=$(echo "$response" | jq -r '.video.url // empty')
        
        if [[ -n "$video_url" ]]; then
            curl -s -o "mobile/scene${scene_num}.mp4" "$video_url"
            if [[ -f "mobile/scene${scene_num}.mp4" ]]; then
                size=$(ls -lh "mobile/scene${scene_num}.mp4" | awk '{print $5}')
                echo "   ✅ Scene $scene_num: Mobile video saved ($size)"
            fi
        else
            echo "   ❌ Scene $scene_num: Failed"
            echo "$response" > "responses/scene${scene_num}_mobile_error.json"
        fi
    ) &
    
    # Limit to 8 concurrent jobs
    if (( (scene % 8) == 0 )); then
        wait
    fi
    
    sleep 2
done

wait  # Wait for all remaining jobs

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Mobile video generation complete!"
echo ""
echo "📊 Status:"
for i in {01..24}; do
    if [[ -f "mobile/scene${i}.mp4" ]]; then
        size=$(ls -lh "mobile/scene${i}.mp4" | awk '{print $5}')
        echo "   ✅ Scene $i: $size"
    else
        echo "   ❌ Scene $i: Missing"
    fi
done

